version: '3'
services:
  dev:
    build:
      context: .
    image: rust-im
    container_name: rust-stucrs-dev
    volumes:
      - type: bind
        source: .
        target: /workdir
    stdin_open: true
    tty: true
    working_dir: /workdir

    environment:
      - USER=user
