[package]
name = "my_scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16"
rand = "0.8"
ndarray-rand = "0.15"
ndarray-stats = "0.6.0"
plotters = "0.3.1"
image = "0.25.8"
stucrs = { path = "../stucrs" }
